site_name: CSA_Wiki
copyright: Copyright &copy; 2023 - 2025 中国民航大学网络安全协会
site_description: 驯海路隔壁白帽子
site_author: 中国民航大学网络安全协会
theme:
  name: material
  logo: images/csa_logo.png
  features:
    - content.code.copy # 代码块复制按钮
    - navigation.tabs # 启用导航栏标签页
  # 配置浅色和深色模式
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - include-markdown
  - search
# 导航栏配置
nav:
  - 首页: index.md
  - 培训资料&&教程集合:
<<<<<<< HEAD
      - 01_VMWare虚拟机的安装与使用: training/25-10-31VMWareWorkstationPro/index.md
=======
      - CTF是什么: training/what-is-ctf.md
      - 环境与工具准备: 
        - 01_VMWare虚拟机的安装与使用: training/tools/vmware/index.md
      - 靶场推荐: training/lab.md
  - CTF技能树:
      - Introduction: ctf/ctf_index.md
      - Web: 
        - xxx: ctf/web/web.md
      - Crypto:
        - xxx: ctf/crypto/crypto.md
      - Pwn:
        - xxx: ctf/pwn/pwn.md
      - Reverse:
        - xxx: ctf/reverse/reverse.md
      - Misc:
        - xxx: ctf/misc/misc.md
>>>>>>> 393a372 (增加nav和目录，修改原有目录结构)
  - wiki建设:
      - 提交规范: contributing/contributing.md
      - 撰写规范: contributing/writing.md